# Generated by Django 6.1.1 on 2026-09-09 22:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('unidad_medida', models.CharField(default='NIU', max_length=5)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=14)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('afectacion_igv', models.CharField(default='10', max_length=2)),
                ('igv', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'verbose_name': 'línea de comprobante',
                'verbose_name_plural': 'líneas de comprobante',
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('01', 'Factura'), ('03', 'Boleta de venta'), ('07', 'Nota de crédito'), ('08', 'Nota de débito'), ('09', 'Guía de remisión')], db_index=True, max_length=2)),
                ('serie', models.CharField(max_length=4)),
                ('correlativo', models.PositiveIntegerField()),
                ('fecha_emision', models.DateField(db_index=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('moneda', models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dólares'), ('EUR', 'Euros')], default='PEN', max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('igv', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_cobrado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('por_enviar', 'En cola de envío'), ('enviado', 'Enviado, esperando CDR'), ('aceptado', 'Aceptado por SUNAT'), ('observado', 'Aceptado con observaciones'), ('rechazado', 'Rechazado por SUNAT'), ('anulado', 'Anulado por comunicación de baja')], db_index=True, default='borrador', max_length=12)),
                ('hash_cpe', models.CharField(blank=True, max_length=100)),
                ('xml_firmado', models.FileField(blank=True, null=True, upload_to='cpe/xml/')),
                ('cdr', models.FileField(blank=True, null=True, upload_to='cpe/cdr/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='cpe/pdf/')),
                ('codigo_respuesta', models.CharField(blank=True, max_length=10)),
                ('mensaje_respuesta', models.TextField(blank=True, help_text='El texto exacto del error que ve la persona en el pedido')),
                ('id_externo', models.CharField(blank=True, db_index=True, max_length=100)),
                ('motivo_nota', models.CharField(blank=True, max_length=120)),
                ('comprobante_afectado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='facturacion.comprobante')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa')),
            ],
            options={
                'verbose_name': 'comprobante',
                'verbose_name_plural': 'comprobantes',
                'ordering': ('-fecha_emision', '-correlativo'),
            },
        ),
    ]
