# Generated by Django 6.1.1 on 2026-09-09 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_initial'),
        ('core', '0001_initial'),
        ('facturacion', '0001_initial'),
        ('terceros', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='ventas.pedido'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='tercero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='terceros.tercero'),
        ),
        migrations.AddField(
            model_name='lineacomprobante',
            name='comprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='facturacion.comprobante'),
        ),
        migrations.AddField(
            model_name='lineacomprobante',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='lineacomprobante',
            name='linea_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_comprobante', to='ventas.lineapedido'),
        ),
        migrations.AddField(
            model_name='lineacomprobante',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_comprobante', to='catalogo.producto'),
        ),
        migrations.AddIndex(
            model_name='comprobante',
            index=models.Index(fields=['empresa', 'estado'], name='facturacion_empresa_9a2f58_idx'),
        ),
        migrations.AddConstraint(
            model_name='comprobante',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo', 'serie', 'correlativo'), name='comprobante_unico_por_correlativo'),
        ),
    ]
