# Generated by Django 6.1.1 on 2026-09-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='codigo_motivo_nota',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
