# Generated by Django 6.1.1 on 2026-09-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(db_index=True, max_length=30)),
                ('fecha', models.DateField(db_index=True)),
                ('glosa', models.CharField(max_length=255)),
                ('generado_automaticamente', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'asiento contable',
                'verbose_name_plural': 'asientos contables',
                'ordering': ('-fecha', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(db_index=True, max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('naturaleza', models.CharField(choices=[('deudora', 'Deudora'), ('acreedora', 'Acreedora')], default='deudora', max_length=10)),
                ('acepta_movimiento', models.BooleanField(default=True, help_text='Las cuentas de agrupación no reciben asientos')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'cuenta contable',
                'verbose_name_plural': 'cuentas contables',
                'ordering': ('codigo',),
            },
        ),
        migrations.CreateModel(
            name='LineaAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('glosa', models.CharField(blank=True, max_length=255)),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'verbose_name': 'línea de asiento',
                'verbose_name_plural': 'líneas de asiento',
            },
        ),
        migrations.CreateModel(
            name='PeriodoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('anio', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('cerrado', models.BooleanField(default=False, help_text='Un periodo cerrado ya no admite asientos nuevos')),
            ],
            options={
                'verbose_name': 'periodo contable',
                'verbose_name_plural': 'periodos contables',
                'ordering': ('-anio', '-mes'),
            },
        ),
        migrations.CreateModel(
            name='ReglaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_documento', models.CharField(help_text='venta_factura, venta_boleta, cobro, pago, compra…', max_length=40)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'regla contable',
                'verbose_name_plural': 'reglas contables',
            },
        ),
    ]
