# Generated by Django 6.1.1 on 2026-09-09 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('core', '0001_initial'),
        ('facturacion', '0001_initial'),
        ('terceros', '0001_initial'),
        ('tesoreria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='comprobante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asientos', to='facturacion.comprobante'),
        ),
        migrations.AddField(
            model_name='asiento',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asiento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='asiento',
            name='movimiento_tesoreria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asientos', to='tesoreria.movimiento'),
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijas', to='contabilidad.cuentacontable'),
        ),
        migrations.AddField(
            model_name='lineaasiento',
            name='asiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='contabilidad.asiento'),
        ),
        migrations.AddField(
            model_name='lineaasiento',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas', to='contabilidad.cuentacontable'),
        ),
        migrations.AddField(
            model_name='lineaasiento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='lineaasiento',
            name='tercero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='terceros.tercero'),
        ),
        migrations.AddField(
            model_name='periodocontable',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='asiento',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asientos', to='contabilidad.periodocontable'),
        ),
        migrations.AddField(
            model_name='reglacontable',
            name='cuenta_debe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglas_debe', to='contabilidad.cuentacontable'),
        ),
        migrations.AddField(
            model_name='reglacontable',
            name='cuenta_haber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglas_haber', to='contabilidad.cuentacontable'),
        ),
        migrations.AddField(
            model_name='reglacontable',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa'),
        ),
        migrations.AddConstraint(
            model_name='cuentacontable',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='cuenta_unica_por_codigo'),
        ),
        migrations.AddConstraint(
            model_name='lineaasiento',
            constraint=models.CheckConstraint(condition=models.Q(('debe', 0), ('haber', 0), _connector='OR'), name='linea_asiento_debe_o_haber'),
        ),
        migrations.AddConstraint(
            model_name='lineaasiento',
            constraint=models.CheckConstraint(condition=models.Q(('debe__gte', 0), ('haber__gte', 0)), name='linea_asiento_sin_negativos'),
        ),
        migrations.AddConstraint(
            model_name='periodocontable',
            constraint=models.UniqueConstraint(fields=('empresa', 'anio', 'mes'), name='periodo_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='asiento',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='asiento_unico_por_numero'),
        ),
        migrations.AddConstraint(
            model_name='reglacontable',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo_documento'), name='regla_unica_por_tipo_documento'),
        ),
    ]
