# Generated by Django 6.1.1 on 2026-09-22 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_initial'),
        ('core', '0003_alter_serie_tipo_documento'),
        ('facturacion', '0003_comprobante_codigo_motivo_nota'),
        ('tesoreria', '0003_movimiento_extorna_a'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCambioCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('moneda', models.CharField(max_length=3)),
                ('tasa', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
            options={
                'verbose_name': 'tipo de cambio de cierre',
                'verbose_name_plural': 'tipos de cambio de cierre',
            },
        ),
        migrations.AddField(
            model_name='asiento',
            name='clave_automatica',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='asiento',
            name='extorna_a',
            field=models.OneToOneField(blank=True, help_text='Asiento original revertido por este asiento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extorno', to='contabilidad.asiento'),
        ),
        migrations.AddConstraint(
            model_name='asiento',
            constraint=models.UniqueConstraint(condition=models.Q(('clave_automatica', ''), _negated=True), fields=('empresa', 'clave_automatica'), name='asiento_clave_automatica_unica'),
        ),
        migrations.AddField(
            model_name='tipocambiocierre',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='tipocambiocierre',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_cambio', to='contabilidad.periodocontable'),
        ),
        migrations.AddConstraint(
            model_name='tipocambiocierre',
            constraint=models.UniqueConstraint(fields=('empresa', 'periodo', 'moneda'), name='tipo_cambio_cierre_unico'),
        ),
    ]
