# Generated by Django 6.1.1 on 2026-09-09 22:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('razon_social', models.CharField(max_length=200)),
                ('nombre_comercial', models.CharField(blank=True, max_length=200)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('direccion_fiscal', models.CharField(blank=True, max_length=255)),
                ('moneda_base', models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dólares'), ('EUR', 'Euros')], default='PEN', max_length=3)),
                ('plan_contable', models.CharField(default='PCGE', help_text='Plan contable que rige los asientos', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ('razon_social',),
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('empresa_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.empresa')),
                ('empresas', models.ManyToManyField(blank=True, related_name='usuarios', to='core.empresa')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LimiteAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('descuento_maximo_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('monto_maximo_venta', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_maximo_compra', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('puede_vender_al_credito', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites', to='core.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'límite de aprobación',
                'verbose_name_plural': 'límites de aprobación',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'empresa'), name='limite_unico_por_usuario_empresa')],
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('modelo', models.CharField(db_index=True, max_length=100)),
                ('objeto_id', models.CharField(db_index=True, max_length=50)),
                ('accion', models.CharField(choices=[('crear', 'Creación'), ('editar', 'Edición'), ('eliminar', 'Eliminación'), ('transicion', 'Cambio de estado')], max_length=20)),
                ('valores_antes', models.JSONField(blank=True, default=dict)),
                ('valores_despues', models.JSONField(blank=True, default=dict)),
                ('canal', models.CharField(default='web', help_text='web, api, portal, tarea programada', max_length=50)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditoria', to='core.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'registros de auditoría',
                'ordering': ('-creado_en',),
                'indexes': [models.Index(fields=['modelo', 'objeto_id'], name='core_regist_modelo_a44527_idx')],
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_documento', models.CharField(help_text='Catálogo 01 SUNAT: 01 factura, 03 boleta, 07 NC, 08 ND', max_length=2)),
                ('serie', models.CharField(max_length=4)),
                ('correlativo_actual', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa')),
            ],
            options={
                'verbose_name': 'serie',
                'verbose_name_plural': 'series',
                'constraints': [models.UniqueConstraint(fields=('empresa', 'tipo_documento', 'serie'), name='serie_unica_por_empresa')],
            },
        ),
    ]
