# Generated by Django 6.1.1 on 2026-09-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='serie',
            field=models.CharField(max_length=12),
        ),
    ]
