# Generated by Django 6.1.1 on 2026-09-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_serie_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='tipo_documento',
            field=models.CharField(help_text='Catálogo 01 SUNAT: 01 factura, 03 boleta, 07 NC, 08 ND; PED/REC internos', max_length=3),
        ),
    ]
