# Generated by Django 6.1.1 on 2026-09-09 22:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('facturacion', '0001_initial'),
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('banco', models.CharField(max_length=80)),
                ('numero', models.CharField(max_length=40)),
                ('cci', models.CharField(blank=True, max_length=20)),
                ('moneda', models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dólares'), ('EUR', 'Euros')], default='PEN', max_length=3)),
                ('cuenta_contable', models.CharField(blank=True, max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa')),
            ],
            options={
                'verbose_name': 'cuenta bancaria',
                'verbose_name_plural': 'cuentas bancarias',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sentido', models.CharField(choices=[('cobro', 'Cobro (entra dinero)'), ('pago', 'Pago (sale dinero)')], db_index=True, max_length=6)),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('deposito', 'Depósito'), ('tarjeta', 'Tarjeta'), ('pasarela', 'Pasarela de pagos'), ('yape_plin', 'Yape o Plin'), ('letra', 'Letra o canje')], max_length=15)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('comision', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('moneda', models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dólares'), ('EUR', 'Euros')], default='PEN', max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=10)),
                ('fecha', models.DateField(db_index=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('conciliado', 'Conciliado con el banco'), ('anulado', 'Anulado')], db_index=True, default='pendiente', max_length=12)),
                ('referencia_externa', models.CharField(blank=True, db_index=True, help_text='Id de la pasarela u operación bancaria, para conciliar', max_length=120)),
                ('notas', models.CharField(blank=True, max_length=255)),
                ('comprobante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='facturacion.comprobante')),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='tesoreria.cuentabancaria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_tesoreria', to='terceros.tercero')),
            ],
            options={
                'verbose_name': 'cobro o pago',
                'verbose_name_plural': 'cobros y pagos',
                'ordering': ('-fecha', '-id'),
            },
        ),
        migrations.CreateModel(
            name='LineaExtractoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(db_index=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Negativo si es cargo', max_digits=14)),
                ('referencia', models.CharField(blank=True, db_index=True, max_length=120)),
                ('conciliada', models.BooleanField(db_index=True, default=False)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_extracto', to='tesoreria.cuentabancaria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa')),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_extracto', to='tesoreria.movimiento')),
            ],
            options={
                'verbose_name': 'línea de extracto bancario',
                'verbose_name_plural': 'líneas de extracto bancario',
                'ordering': ('-fecha',),
            },
        ),
        migrations.AddConstraint(
            model_name='cuentabancaria',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='cuenta_unica_por_numero'),
        ),
        migrations.AddConstraint(
            model_name='movimiento',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='monto_positivo'),
        ),
    ]
