# Generated by Django 6.1.1 on 2026-09-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_serie_serie'),
        ('facturacion', '0002_initial'),
        ('terceros', '0002_alter_tercero_options'),
        ('tesoreria', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='movimiento',
            constraint=models.UniqueConstraint(condition=models.Q(('referencia_externa', ''), _negated=True), fields=('empresa', 'sentido', 'referencia_externa'), name='movimiento_referencia_unica'),
        ),
    ]
