# Generated by Django 6.1.1 on 2026-09-22 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0002_movimiento_movimiento_referencia_unica'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='extorna_a',
            field=models.OneToOneField(blank=True, help_text='Movimiento original que este pago inverso extorna', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extorno', to='tesoreria.movimiento'),
        ),
    ]
