# Generated by Django 6.1.1 on 2026-09-09 22:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(choices=[('ose', 'OSE / facturación electrónica'), ('pasarela', 'Pasarela de pagos'), ('banco', 'Banco'), ('crm', 'CRM de marketing'), ('whatsapp', 'WhatsApp Business'), ('ads', 'Meta o Google Ads'), ('tienda', 'Tienda en línea'), ('drive', 'Google Workspace'), ('automatizacion', 'n8n, Make o Zapier')], db_index=True, max_length=20)),
                ('nombre', models.CharField(max_length=120)),
                ('proveedor', models.CharField(blank=True, help_text='Nubefact, Culqi, Shopify…', max_length=80)),
                ('url_base', models.URLField(blank=True)),
                ('credenciales', models.JSONField(blank=True, default=dict, help_text='Token, llave o datos de OAuth del servicio')),
                ('secreto_webhook', models.CharField(blank=True, help_text='Con esto se valida la firma de lo que llega', max_length=200)),
                ('modo_simulado', models.BooleanField(default=True, help_text='Mientras esté activo no se llama al servicio real')),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa')),
            ],
            options={
                'verbose_name': 'servicio externo',
                'verbose_name_plural': 'servicios externos',
            },
        ),
        migrations.CreateModel(
            name='RegistroIntegracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('direccion', models.CharField(choices=[('salida', 'Sale del ERP'), ('entrada', 'Entra al ERP')], db_index=True, max_length=8)),
                ('operacion', models.CharField(help_text='emitir_comprobante, crear_contacto…', max_length=80)),
                ('entidad', models.CharField(blank=True, max_length=60)),
                ('objeto_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('id_externo', models.CharField(blank=True, db_index=True, max_length=120)),
                ('contenido_enviado', models.JSONField(blank=True, default=dict)),
                ('contenido_recibido', models.JSONField(blank=True, default=dict)),
                ('codigo_http', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('exito', 'Con respuesta correcta'), ('error', 'Con error'), ('descartado', 'Descartado tras agotar reintentos')], db_index=True, default='pendiente', max_length=12)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('mensaje_error', models.TextField(blank=True)),
                ('duracion_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='integraciones.servicioexterno')),
            ],
            options={
                'verbose_name': 'registro de integración',
                'verbose_name_plural': 'registros de integración',
                'ordering': ('-creado_en',),
            },
        ),
        migrations.CreateModel(
            name='MapeoCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('entidad', models.CharField(help_text='tercero, producto, pedido, comprobante…', max_length=60)),
                ('campo_erp', models.CharField(max_length=80)),
                ('campo_externo', models.CharField(max_length=120)),
                ('transformacion', models.CharField(blank=True, help_text='mayusculas, fecha_iso, solo_digitos…', max_length=80)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeos', to='integraciones.servicioexterno')),
            ],
            options={
                'verbose_name': 'mapeo de campo',
                'verbose_name_plural': 'mapeos de campo',
            },
        ),
        migrations.CreateModel(
            name='EventoWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('evento', models.CharField(db_index=True, max_length=80)),
                ('id_evento_externo', models.CharField(blank=True, db_index=True, max_length=140)),
                ('cuerpo', models.JSONField(blank=True, default=dict)),
                ('cabeceras', models.JSONField(blank=True, default=dict)),
                ('firma_valida', models.BooleanField(default=False)),
                ('procesado', models.BooleanField(db_index=True, default=False)),
                ('mensaje_error', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhooks', to='integraciones.servicioexterno')),
            ],
            options={
                'verbose_name': 'evento de webhook',
                'verbose_name_plural': 'eventos de webhook',
                'ordering': ('-creado_en',),
            },
        ),
        migrations.CreateModel(
            name='TrabajoIntegracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('operacion', models.CharField(db_index=True, max_length=80)),
                ('carga', models.JSONField(blank=True, default=dict)),
                ('entidad', models.CharField(blank=True, max_length=60)),
                ('objeto_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('llave_idempotencia', models.CharField(db_index=True, max_length=120)),
                ('estado', models.CharField(choices=[('en_cola', 'En cola'), ('en_proceso', 'En proceso'), ('hecho', 'Hecho'), ('reintentar', 'Esperando reintento'), ('fallido', 'En la cola de errores')], db_index=True, default='en_cola', max_length=12)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('ejecutar_despues_de', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ultimo_error', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajos', to='integraciones.servicioexterno')),
            ],
            options={
                'verbose_name': 'trabajo de integración',
                'verbose_name_plural': 'trabajos de integración',
                'ordering': ('ejecutar_despues_de',),
            },
        ),
        migrations.AddConstraint(
            model_name='servicioexterno',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo', 'nombre'), name='servicio_unico_por_empresa'),
        ),
        migrations.AddIndex(
            model_name='registrointegracion',
            index=models.Index(fields=['servicio', 'estado'], name='integracion_servici_8a0c6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='mapeocampo',
            constraint=models.UniqueConstraint(fields=('servicio', 'entidad', 'campo_erp'), name='mapeo_unico_por_campo'),
        ),
        migrations.AddConstraint(
            model_name='eventowebhook',
            constraint=models.UniqueConstraint(condition=models.Q(('id_evento_externo', ''), _negated=True), fields=('servicio', 'id_evento_externo'), name='webhook_no_duplicado'),
        ),
        migrations.AddConstraint(
            model_name='trabajointegracion',
            constraint=models.UniqueConstraint(fields=('servicio', 'llave_idempotencia'), name='trabajo_idempotente'),
        ),
    ]
