# Generated by Django 6.1.1 on 2026-09-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('integraciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventowebhook',
            name='webhook_no_duplicado',
        ),
        migrations.AddConstraint(
            model_name='eventowebhook',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('id_evento_externo', ''), _negated=True), ('firma_valida', True)), fields=('servicio', 'id_evento_externo'), name='webhook_no_duplicado'),
        ),
    ]
