# Generated by Django 6.1.1 on 2026-09-09 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('interna', 'Interna'), ('proveedor', 'Virtual — proveedor'), ('cliente', 'Virtual — cliente'), ('ajuste', 'Virtual — ajuste de inventario'), ('transito', 'Virtual — en tránsito')], default='interna', max_length=15)),
            ],
            options={
                'verbose_name': 'ubicación',
                'verbose_name_plural': 'ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('ubigeo', models.CharField(blank=True, max_length=6)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='almacenes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'almacén',
                'verbose_name_plural': 'almacenes',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=60)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'lote',
                'verbose_name_plural': 'lotes',
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=4, help_text='Siempre positiva: el sentido lo dan las ubicaciones', max_digits=14)),
                ('numero_serie', models.CharField(blank=True, max_length=80)),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('fecha', models.DateTimeField(db_index=True)),
                ('documento_origen', models.CharField(blank=True, db_index=True, max_length=60)),
                ('documento_tipo', models.CharField(blank=True, max_length=40)),
                ('documento_id', models.CharField(blank=True, max_length=40)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='catalogo.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'movimiento de stock',
                'verbose_name_plural': 'movimientos de stock',
                'ordering': ('-fecha',),
            },
        ),
        migrations.CreateModel(
            name='ReservaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('consumida', 'Consumida por la salida'), ('liberada', 'Liberada')], db_index=True, default='activa', max_length=12)),
                ('documento_origen', models.CharField(blank=True, db_index=True, max_length=60)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa')),
            ],
            options={
                'verbose_name': 'reserva de stock',
                'verbose_name_plural': 'reservas de stock',
            },
        ),
    ]
