# Generated by Django 6.1.1 on 2026-09-09 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_initial'),
        ('core', '0001_initial'),
        ('inventario', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservastock',
            name='linea_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='ventas.lineapedido'),
        ),
        migrations.AddField(
            model_name='reservastock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='catalogo.producto'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='inventario.almacen'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='reservastock',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='inventario.ubicacion'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_entrada', to='inventario.ubicacion'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_salida', to='inventario.ubicacion'),
        ),
        migrations.AddConstraint(
            model_name='almacen',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='almacen_unico_por_codigo'),
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.UniqueConstraint(fields=('empresa', 'producto', 'codigo'), name='lote_unico_por_producto'),
        ),
        migrations.AddConstraint(
            model_name='ubicacion',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='ubicacion_unica_por_codigo'),
        ),
        migrations.AddConstraint(
            model_name='reservastock',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='reserva_cantidad_positiva'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['producto', 'fecha'], name='inventario__product_fc780a_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimientostock',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='movimientostock',
            constraint=models.CheckConstraint(condition=models.Q(('origen', models.F('destino')), _negated=True), name='origen_distinto_de_destino'),
        ),
    ]
