# Generated by Django 6.1.1 on 2026-09-19 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventario', '0002_initial'),
        ('terceros', '0002_alter_tercero_options'),
        ('ventas', '0002_alter_pedido_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('serie', models.CharField(max_length=4)),
                ('correlativo', models.PositiveIntegerField()),
                ('fecha_emision', models.DateField()),
                ('fecha_traslado', models.DateField()),
                ('motivo', models.CharField(choices=[('01', 'Venta'), ('02', 'Compra'), ('04', 'Traslado entre establecimientos'), ('06', 'Devolución'), ('13', 'Otros')], default='01', max_length=2)),
                ('modalidad', models.CharField(choices=[('01', 'Transporte público'), ('02', 'Transporte privado')], default='02', max_length=2)),
                ('punto_partida', models.CharField(max_length=255)),
                ('punto_llegada', models.CharField(max_length=255)),
                ('transportista', models.CharField(blank=True, max_length=150)),
                ('placa', models.CharField(blank=True, max_length=10)),
                ('conductor_documento', models.CharField(blank=True, max_length=15)),
                ('peso_kg', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('bultos', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('por_enviar', 'En cola de envío'), ('enviado', 'Enviado, esperando CDR'), ('aceptado', 'Aceptado por SUNAT'), ('rechazado', 'Rechazado por SUNAT')], db_index=True, default='borrador', max_length=12)),
                ('id_externo', models.CharField(blank=True, max_length=100)),
                ('mensaje_respuesta', models.TextField(blank=True)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias', to='terceros.tercero')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guias', to='ventas.pedido')),
            ],
            options={
                'verbose_name': 'guía de remisión',
                'verbose_name_plural': 'guías de remisión',
                'ordering': ('-fecha_emision', '-correlativo'),
                'constraints': [models.UniqueConstraint(fields=('empresa', 'serie', 'correlativo'), name='guia_unica_por_correlativo')],
            },
        ),
    ]
