# Generated by Django 6.1.1 on 2026-09-24 16:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalogo', '0002_initial'),
        ('compras', '0005_alter_ordencompra_options_alter_recepcion_options'),
        ('contabilidad', '0003_tipocambiocierre_asiento_clave_automatica_and_more'),
        ('core', '0003_alter_serie_tipo_documento'),
        ('inventario', '0003_guiaremision'),
        ('terceros', '0002_alter_tercero_options'),
        ('tesoreria', '0003_movimiento_extorna_a'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=40)),
                ('fecha', models.DateField()),
                ('vencimiento', models.DateField()),
                ('moneda', models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dólares'), ('EUR', 'Euros')], default='PEN', max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('concepto', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('borrador', 'Por aprobar'), ('aprobada', 'Aprobada')], default='borrador', max_length=15)),
                ('aprobada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('asiento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.asiento')),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cuentacontable')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='compras.ordencompra')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='terceros.tercero')),
            ],
            options={
                'ordering': ('vencimiento', 'pk'),
                'permissions': [('aprobar_factura', 'Puede aprobar facturas de proveedor'), ('pagar_factura', 'Puede registrar pagos a proveedores')],
            },
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa')),
                ('roles', models.ManyToManyField(blank=True, to='auth.group')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperacionInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('clave', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('transferencia', 'Transferencia'), ('conteo', 'Conteo físico'), ('devolucion', 'Devolución de movimiento')], max_length=15)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('existencia_esperada', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('motivo', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Por aprobar'), ('hecho', 'Aplicada')], default='pendiente', max_length=15)),
                ('aprobada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventario.ubicacion')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa')),
                ('movimiento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventario.movimientostock')),
                ('movimiento_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventario.movimientostock')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventario.ubicacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.producto')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-creado_en',),
                'permissions': [('aprobar_inventario', 'Puede aprobar ajustes, transferencias y devoluciones')],
            },
        ),
        migrations.CreateModel(
            name='PagoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='gestion.facturaproveedor')),
                ('movimiento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pago_proveedor', to='tesoreria.movimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('rubro', models.CharField(blank=True, max_length=100)),
                ('contabilizar_inventario', models.BooleanField(default=False, help_text='Activar después de configurar costo_venta y ajuste_inventario y validar saldos iniciales.')),
                ('correo_soporte', models.EmailField(blank=True, max_length=254)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='perfil', to='core.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='facturaproveedor',
            constraint=models.UniqueConstraint(fields=('empresa', 'proveedor', 'numero'), name='factura_proveedor_unica'),
        ),
        migrations.AddConstraint(
            model_name='facturaproveedor',
            constraint=models.CheckConstraint(condition=models.Q(('impuestos__gte', 0), ('subtotal__gte', 0)), name='factura_proveedor_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='membresia',
            constraint=models.UniqueConstraint(fields=('empresa', 'usuario'), name='membresia_empresa_usuario'),
        ),
    ]
