# Generated by Django 6.1.1 on 2026-09-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'categoría de producto',
                'verbose_name_plural': 'categorías de producto',
            },
        ),
        migrations.CreateModel(
            name='ListaPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('moneda', models.CharField(default='PEN', max_length=3)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'lista de precios',
                'verbose_name_plural': 'listas de precios',
            },
        ),
        migrations.CreateModel(
            name='PrecioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('precio', models.DecimalField(decimal_places=4, max_digits=14)),
                ('cantidad_minima', models.DecimalField(decimal_places=4, default=1, max_digits=14)),
            ],
            options={
                'verbose_name': 'precio de producto',
                'verbose_name_plural': 'precios de producto',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(db_index=True, max_length=40)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('bien', 'Bien'), ('servicio', 'Servicio')], default='bien', max_length=10)),
                ('precio_lista', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('costo_promedio', models.DecimalField(decimal_places=4, default=0, help_text='Lo recalcula el módulo de inventario en cada ingreso', max_digits=14)),
                ('afectacion_igv', models.CharField(choices=[('10', 'Gravado - operación onerosa'), ('20', 'Exonerado'), ('30', 'Inafecto'), ('11', 'Gravado - retiro por bonificación')], default='10', max_length=2)),
                ('controla_stock', models.BooleanField(default=True)),
                ('controla_lotes', models.BooleanField(default=False)),
                ('controla_series', models.BooleanField(default=False)),
                ('stock_minimo', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('ids_externos', models.JSONField(blank=True, default=dict)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ('codigo',),
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'unidad de medida',
                'verbose_name_plural': 'unidades de medida',
            },
        ),
    ]
