# Generated by Django 6.1.1 on 2026-09-09 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproducto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijas', to='catalogo.categoriaproducto'),
        ),
        migrations.AddField(
            model_name='listaprecios',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='precioproducto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='precioproducto',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='catalogo.listaprecios'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='catalogo.categoriaproducto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='precioproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='catalogo.producto'),
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.unidadmedida'),
        ),
        migrations.AddConstraint(
            model_name='precioproducto',
            constraint=models.UniqueConstraint(fields=('lista', 'producto', 'cantidad_minima'), name='precio_unico_por_escala'),
        ),
        migrations.AddConstraint(
            model_name='unidadmedida',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='unidad_unica_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='producto_unico_por_codigo'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('tipo', 'bien'), ('controla_stock', False), _connector='OR'), name='servicio_no_controla_stock'),
        ),
    ]
