# Generated by Django 6.1.1 on 2026-09-09 22:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineaOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=14)),
                ('tasa_impuesto', models.DecimalField(decimal_places=4, default=Decimal('0.18'), max_digits=5)),
                ('cantidad_recibida', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
            ],
            options={
                'verbose_name': 'línea de orden de compra',
                'verbose_name_plural': 'líneas de orden de compra',
            },
        ),
        migrations.CreateModel(
            name='LineaRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
            ],
            options={
                'verbose_name': 'línea de recepción',
                'verbose_name_plural': 'líneas de recepción',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(db_index=True, max_length=30)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('por_aprobar', 'Esperando aprobación'), ('aprobada', 'Aprobada'), ('enviada', 'Enviada al proveedor'), ('recibida_parcial', 'Recibida parcialmente'), ('recibida', 'Recibida'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], db_index=True, default='borrador', max_length=20)),
                ('fecha', models.DateField()),
                ('fecha_entrega_esperada', models.DateField(blank=True, null=True)),
                ('moneda', models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dólares'), ('EUR', 'Euros')], default='PEN', max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'orden de compra',
                'verbose_name_plural': 'órdenes de compra',
                'ordering': ('-fecha', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(db_index=True, max_length=30)),
                ('fecha', models.DateField()),
                ('guia_proveedor', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'verbose_name': 'recepción',
                'verbose_name_plural': 'recepciones',
            },
        ),
    ]
