# Generated by Django 6.1.1 on 2026-09-09 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_initial'),
        ('compras', '0002_initial'),
        ('core', '0001_initial'),
        ('inventario', '0001_initial'),
        ('terceros', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='linearecepcion',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventario.lote'),
        ),
        migrations.AddField(
            model_name='linearecepcion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_recepcion', to='catalogo.producto'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='almacen_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='inventario.almacen'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='aprobada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='pedido_origen',
            field=models.ForeignKey(blank=True, help_text='Cuando la compra nace de un pedido sin stock', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='ventas.pedido'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='terceros.tercero'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lineaordencompra',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='compras.ordencompra'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='inventario.almacen'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='compras.ordencompra'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='recibido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='linearecepcion',
            name='recepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='compras.recepcion'),
        ),
        migrations.AddConstraint(
            model_name='ordencompra',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='orden_compra_unica_por_numero'),
        ),
        migrations.AddConstraint(
            model_name='lineaordencompra',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='linea_oc_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='recepcion',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='recepcion_unica_por_numero'),
        ),
    ]
