# Generated by Django 6.1.1 on 2026-09-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recepcion',
            options={'permissions': [('aprobar_ordencompra', 'Puede aprobar órdenes de compra')], 'verbose_name': 'recepción', 'verbose_name_plural': 'recepciones'},
        ),
    ]
