# Generated by Django 6.1.1 on 2026-09-21 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_recepcion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'ordering': ('-fecha', '-id'), 'permissions': [('aprobar_ordencompra', 'Puede aprobar órdenes de compra')], 'verbose_name': 'orden de compra', 'verbose_name_plural': 'órdenes de compra'},
        ),
        migrations.AlterModelOptions(
            name='recepcion',
            options={'verbose_name': 'recepción', 'verbose_name_plural': 'recepciones'},
        ),
    ]
