# Generated by Django 6.1.1 on 2026-09-19 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('terceros', '0002_alter_tercero_options'),
        ('ventas', '0002_alter_pedido_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Persona o empresa que dejó sus datos', max_length=150)),
                ('empresa_lead', models.CharField(blank=True, max_length=150, verbose_name='empresa del contacto')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('telefono', models.CharField(blank=True, db_index=True, max_length=30)),
                ('numero_documento', models.CharField(blank=True, db_index=True, max_length=15)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('calificado', 'Calificado'), ('propuesta', 'Con propuesta'), ('ganado', 'Ganado'), ('perdido', 'Perdido')], db_index=True, default='nuevo', max_length=12)),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('origen', models.CharField(blank=True, db_index=True, help_text='meta_ads, google_ads, web, whatsapp, referido…', max_length=60)),
                ('campania', models.CharField(blank=True, max_length=120)),
                ('utm', models.JSONField(blank=True, default=dict)),
                ('id_externo', models.CharField(blank=True, db_index=True, max_length=120)),
                ('interes', models.TextField(blank=True, help_text='Qué quiere, en sus palabras')),
                ('motivo_perdida', models.CharField(blank=True, max_length=120)),
                ('conversion_enviada', models.BooleanField(default=False, help_text='Ya se avisó a la plataforma de anuncios con el valor real')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='ventas.pedido')),
                ('tercero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='terceros.tercero')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'ordering': ('-creado_en',),
                'permissions': [('ver_todo', 'Puede ver los leads de todos los vendedores')],
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('llamada', 'Llamada'), ('whatsapp', 'WhatsApp'), ('correo', 'Correo'), ('reunion', 'Reunión'), ('nota', 'Nota')], default='nota', max_length=10)),
                ('detalle', models.TextField()),
                ('programada_para', models.DateTimeField(blank=True, null=True)),
                ('hecha', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='crm.lead')),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
                'ordering': ('-creado_en',),
            },
        ),
    ]
