# Generated by Django 6.1.1 on 2026-09-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ('-creado_en',), 'permissions': [('ver_todo', 'Puede ver los leads de todos los vendedores'), ('recibir_leads', 'Entra en el reparto automático de leads')], 'verbose_name': 'lead', 'verbose_name_plural': 'leads'},
        ),
        migrations.AddField(
            model_name='actividad',
            name='es_entrante',
            field=models.BooleanField(default=False, help_text='Lo escribió el cliente, no nosotros'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='programada_para',
            field=models.DateTimeField(blank=True, help_text='Para agendar el próximo contacto: «llamar el jueves»', null=True),
        ),
    ]
