# Generated by Django 6.1.1 on 2026-09-23 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_serie_tipo_documento'),
        ('crm', '0002_alter_lead_options_actividad_es_entrante_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='cierre_esperado',
            field=models.DateField(blank=True, help_text='Fecha prevista de la venta', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='equipo_ventas',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='etiquetas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de etiquetas propias, ej. ["cliente caliente"]'),
        ),
        migrations.AddField(
            model_name='lead',
            name='idioma',
            field=models.CharField(blank=True, help_text='Idioma del cliente, ej. Español', max_length=40),
        ),
        migrations.AddField(
            model_name='lead',
            name='medio',
            field=models.CharField(blank=True, help_text='Facebook, Google, email, etc.', max_length=60),
        ),
        migrations.AddField(
            model_name='lead',
            name='movil',
            field=models.CharField(blank=True, help_text='Número celular, si es distinto del de contacto', max_length=30, verbose_name='móvil'),
        ),
        migrations.AddField(
            model_name='lead',
            name='notas_internas',
            field=models.TextField(blank=True, help_text='Comentarios del vendedor, no visibles para el cliente'),
        ),
        migrations.AddField(
            model_name='lead',
            name='pais',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='prioridad',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin prioridad'), (1, 'Baja'), (2, 'Media'), (3, 'Alta')], default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='probabilidad',
            field=models.PositiveSmallIntegerField(default=0, help_text='Probabilidad estimada de cierre, de 0 a 100'),
        ),
        migrations.AddField(
            model_name='lead',
            name='referido_por',
            field=models.CharField(blank=True, help_text='Persona o canal que originó el lead', max_length=150),
        ),
        migrations.AddField(
            model_name='lead',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='estado / región'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='valor_estimado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='ingreso esperado'),
        ),
        migrations.CreateModel(
            name='ArchivoLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('archivo', models.FileField(upload_to='crm/archivos/%Y/%m/')),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='crm.lead')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'archivo del lead',
                'verbose_name_plural': 'archivos del lead',
                'ordering': ('-creado_en',),
            },
        ),
    ]
