# Generated by Django 6.1.1 on 2026-09-23 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_serie_tipo_documento'),
        ('crm', '0003_lead_cierre_esperado_lead_ciudad_lead_direccion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltroGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('vista', models.CharField(choices=[('lista', 'Lista'), ('embudo', 'Embudo')], default='lista', max_length=10)),
                ('nombre', models.CharField(max_length=80)),
                ('querystring', models.CharField(blank=True, max_length=500)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtros_crm', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'filtro guardado',
                'verbose_name_plural': 'filtros guardados',
                'ordering': ('nombre',),
            },
        ),
    ]
