# Generated by Django 6.1.1 on 2026-09-09 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=80)),
                ('dias', models.PositiveSmallIntegerField(default=0, help_text='0 = contado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa')),
            ],
            options={
                'verbose_name': 'condición de pago',
                'verbose_name_plural': 'condiciones de pago',
            },
        ),
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('es_cliente', models.BooleanField(default=True)),
                ('es_proveedor', models.BooleanField(default=False)),
                ('tipo_documento', models.CharField(choices=[('1', 'DNI'), ('4', 'Carné de extranjería'), ('6', 'RUC'), ('7', 'Pasaporte'), ('0', 'Otro')], default='1', max_length=1)),
                ('numero_documento', models.CharField(db_index=True, max_length=15)),
                ('razon_social', models.CharField(max_length=200)),
                ('nombre_comercial', models.CharField(blank=True, max_length=200)),
                ('direccion_fiscal', models.CharField(blank=True, max_length=255)),
                ('ubigeo', models.CharField(blank=True, max_length=6)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('linea_credito', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ids_externos', models.JSONField(blank=True, default=dict, help_text='Id en cada servicio externo, por ejemplo hubspot o shopify')),
                ('activo', models.BooleanField(default=True)),
                ('condicion_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terceros', to='terceros.condicionpago')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa')),
                ('vendedor_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tercero',
                'verbose_name_plural': 'terceros',
                'ordering': ('razon_social',),
            },
        ),
        migrations.CreateModel(
            name='DireccionEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('etiqueta', models.CharField(help_text='Almacén central, tienda Miraflores…', max_length=80)),
                ('direccion', models.CharField(max_length=255)),
                ('ubigeo', models.CharField(blank=True, max_length=6)),
                ('referencia', models.CharField(blank=True, max_length=255)),
                ('es_principal', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='terceros.tercero')),
            ],
            options={
                'verbose_name': 'dirección de entrega',
                'verbose_name_plural': 'direcciones de entrega',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='terceros.tercero')),
            ],
            options={
                'verbose_name': 'contacto',
                'verbose_name_plural': 'contactos',
            },
        ),
        migrations.AddIndex(
            model_name='tercero',
            index=models.Index(fields=['empresa', 'es_cliente'], name='terceros_te_empresa_4884e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='tercero',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo_documento', 'numero_documento'), name='tercero_unico_por_documento'),
        ),
    ]
