# Generated by Django 6.1.1 on 2026-09-19 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tercero',
            options={'ordering': ('razon_social',), 'permissions': [('ver_todo', 'Puede ver los terceros de todos los vendedores')], 'verbose_name': 'tercero', 'verbose_name_plural': 'terceros'},
        ),
    ]
