# Generated by Django 6.1.1 on 2026-09-09 22:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_initial'),
        ('core', '0001_initial'),
        ('inventario', '0001_initial'),
        ('terceros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(db_index=True, max_length=30)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Cotización enviada'), ('confirmado', 'Confirmado'), ('reservado', 'Reservado'), ('entregado', 'Entregado'), ('facturado', 'Facturado'), ('pagado', 'Pagado'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado'), ('vencida', 'Vencida'), ('en_espera', 'En espera de stock')], db_index=True, default='borrador', max_length=15)),
                ('fecha', models.DateField()),
                ('valido_hasta', models.DateField(blank=True, help_text='Vencida esta fecha la cotización pasa a «vencida»', null=True)),
                ('moneda', models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dólares'), ('EUR', 'Euros')], default='PEN', max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=10)),
                ('origen', models.CharField(blank=True, help_text='tienda web, whatsapp, campaña, mostrador…', max_length=60)),
                ('campania', models.CharField(blank=True, max_length=120)),
                ('utm', models.JSONField(blank=True, default=dict)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notas', models.TextField(blank=True)),
                ('ids_externos', models.JSONField(blank=True, default=dict)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='inventario.almacen')),
                ('direccion_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='terceros.direccionentrega')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='terceros.tercero')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pedido de venta',
                'verbose_name_plural': 'pedidos de venta',
                'ordering': ('-fecha', '-id'),
            },
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=14)),
                ('descuento_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tasa_impuesto', models.DecimalField(decimal_places=4, default=Decimal('0.18'), max_digits=5)),
                ('cantidad_entregada', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('cantidad_facturada', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_pedido', to='catalogo.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='ventas.pedido')),
            ],
            options={
                'verbose_name': 'línea de pedido',
                'verbose_name_plural': 'líneas de pedido',
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['empresa', 'estado'], name='ventas_pedi_empresa_03bba2_idx'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='pedido_unico_por_numero'),
        ),
        migrations.AddConstraint(
            model_name='lineapedido',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='linea_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='lineapedido',
            constraint=models.CheckConstraint(condition=models.Q(('descuento_pct__gte', 0), ('descuento_pct__lte', 100)), name='descuento_entre_0_y_100'),
        ),
    ]
