# Generated by Django 6.1.1 on 2026-09-19 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ('-fecha', '-id'), 'permissions': [('ver_todo', 'Puede ver los pedidos de todos los vendedores')], 'verbose_name': 'pedido de venta', 'verbose_name_plural': 'pedidos de venta'},
        ),
    ]
